service: solstice-api

provider:
  name: aws
  runtime: "nodejs10.x"
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:DeleteObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref": "ServerlessDeploymentBucket"
            - "/*"
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.s3JsonBucket}/*"
functions:
  customers:
    handler: handler.customers
    events:
      - http:
          path: customers
          method: get
          cors: true
    environment:
      BUCKET_NAME: ${self:custom.s3JsonBucket}
      FILE_NAME: "initial.json"
  accounts:
    handler: handler.accounts
    events:
      - http:
          path: accounts
          method: get
          cors: true
    environment:
      BUCKET_NAME: ${self:custom.s3JsonBucket}
      FILE_NAME: "initial.json"
plugins:
  - serverless-webpack

custom:
  s3JsonBucket: "solstice-json-bucket"

resources:
  Resources:
    JsonBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3JsonBucket}
